import type { Metadata, Viewport } from "next";
import "@/styles/globals.css";
import { satoshi } from "@/styles/fonts";
import TopBanner from "@/components/layout/Banner/TopBanner";
import TopNavbar from "@/components/layout/Navbar/TopNavbar";
import Footer from "@/components/layout/Footer";
import Providers from "./providers";
import ReactQueryProvider from './ReactQueryProvider'; // ✅
import Loader from "./loader";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Shopco",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="en">
      <body className={satoshi.className}>
        <ReactQueryProvider>
          <Toaster position="top-right" reverseOrder={false} />
          <Loader />
          <TopBanner />
          <Providers>
            <TopNavbar />
            {children}
          </Providers>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>

  );
}